# Generated by Django 5.0.6 on 2024-06-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('identifiant', models.CharField(max_length=200, unique=True)),
                ('mot_de_passe', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('mail', models.CharField(max_length=256)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
