# Generated by Django 5.0.6 on 2024-06-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('commentaire', models.TextField()),
                ('date_de_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
