name: Bonus Project CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and run tests
      run: |
        docker-compose -f Bonus/docker-compose.yml up --build --abort-on-container-exit